FROM node:5.4
MAINTAINER sharils <sharils@users.noreply.github.com>

RUN npm install webpack -g
RUN npm install webpack-dev-server -g
RUN apt-get update
RUN apt-get install -y vim
RUN echo syntax on >> ~/.vimrc
RUN echo set bg=dark >> ~/.vimrc
